
<p align="center">
  <img src="https://i.imgur.com/baO3oqB.gif" width="300" alt="anime aesthetic">
</p>

---

## ğŸ“Š GitHub Stats
<p align="center">
  <img src="https://github-readme-stats.vercel.app/api?username=void-daksh&show_icons=true&theme=tokyonight" />
</p>

<p align="center">
  <img src="https://github-readme-streak-stats.herokuapp.com/?user=void-daksh&theme=tokyonight" />
</p>

---

## ğŸŒŒ Connect With Me
<p align="center">
  <img src="https://i.imgur.com/a76tI2o.gif" width="200">
</p>

---

### â­ If you like my profile, consider giving a â­ to my repos!
